source 'https://rubygems.org'

ruby '2.6.2'

group :development do
  gem 'helloworld'
  gem 'sinatra'
  gem 'nokogiri'
  gem 'capybara'
end

group :development, :test do
  gem 'pry'
  gem 'rake', require: false
end

group :test do
  gem 'rspec', require: false
  gem 'simplecov', require: false
end
